version: '3.9'

services:

  db:
    container_name: delivery_service_container
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: delivery_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

